version: "3"
services:
  backend:
    build: .
    depends_on:
      - "mysql"
    links:
      - mysql
    ports:
      - "8081:8080"
  mysql:
    image: mysql:8
    ports:
      - "192.168.0.102:3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: love

#server:s
#  port: 8080
#db:
#  port: 3307
#  name: love
#  endpoint: mysql-container
#  username: root
#  password: 123456
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysql-container:3307/love?useSSL=false&serverTimezone=UTC
#    username: root
#    password: 123456

#version: '3'
#services:
#  mysql-container:
#    image: mysql:latest
#    container_name: mysql-container
#    environment:
#      - MYSQL_ROOT_PASSWORD=123456
#      - MYSQL_DATABASE=love
#    ports:
#      - '3307:3306'